name: Merge Bot

on:
  status: {} # try to merge when other checks are completed
  pull_request:
    types:
      - labeled
      - ready_for_review
      - review_request_removed
      - review_requested
      - synchronize
      - unlabeled
  pull_request_review:
    types:
      - dismissed
      - submitted

jobs:
  merge:
    runs-on: ubuntu-latest
    name: Merge
    steps:
    - name: Integration check
      uses: squalrus/merge-bot@v0.4.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        test: true 
        reviewers: true
        blocking_labels: do not merge
        checks_enabled: true
        method: merge
