# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  build-asset-pack:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: 'Copy assets'
        run: |
          mkdir -p data/asset-builder/css; \
          cp -r css data/asset-builder
      - name: 'Switch to assets context'
        run: cd data/asset-builder
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@jaapio'
      - run: |
          cd data/asset-builder; \
          npm install
      - run: |
          cd data/asset-builder; \
          npm version prerelease --preid=build
      - run: |
          cd data/asset-builder; \
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push back package version
        uses: devops-infra/action-commit-push@0.1
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          commit_prefix: "[AUTO]"
          commit_message: "Assets package version bump"

