name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Changelog
        run: echo "# Good things have arrived" > ${{ github.workflow }}-CHANGELOG.txt
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          owner: jaapio
          repo: shim
          token: ${{ secrets.GITHUB_TOKEN }}
