name: 'Template Sync'
on:  
  push:
    branches: master

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: narrowspark/template-sync-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_author_name: phpDoc Bot
          git_author_email: bot@phpdoc.org
          template_repository: ergebnis/php-library-template
          ref: refs/heads/master
